basePath: /
definitions:
  authdto.RequestLoginWithHealthId:
    properties:
      code:
        type: string
      redirect_uri:
        type: string
    required:
    - code
    - redirect_uri
    type: object
  dto.BaseResponse:
    properties:
      data: {}
      message_en:
        example: Example created successfully
        type: string
      message_th:
        example: สร้างตัวอย่างสำเร็จ
        type: string
      status:
        example: success
        type: string
      status_code:
        example: 200
        type: integer
    type: object
  exampledto.ExampleRequest:
    properties:
      detail:
        type: string
    type: object
info:
  contact: {}
  description: API for Standard Struct Golang API
  title: Standard Struct Golang API
  version: "1.0"
paths:
  /v1/auth/LoginWithProviderId:
    post:
      consumes:
      - application/json
      description: Login with Health ID
      parameters:
      - description: Login with Health ID
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/authdto.RequestLoginWithHealthId'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.BaseResponse'
      summary: Login with Health ID
      tags:
      - Auth
  /v1/example/:
    post:
      consumes:
      - application/json
      description: คำอธิบาย API Create a new example
      parameters:
      - description: Example request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/exampledto.ExampleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Example created successfully
          schema:
            $ref: '#/definitions/dto.BaseResponse'
      summary: Create a new example
      tags:
      - Example (ตัวอย่าง)
  /v1/example/{example_id}:
    get:
      consumes:
      - application/json
      description: คำอธิบาย API Get an example by ID
      parameters:
      - description: Example ID
        in: path
        name: example_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Example retrieved successfully
          schema:
            $ref: '#/definitions/dto.BaseResponse'
      summary: Get an example by ID
      tags:
      - Example (ตัวอย่าง)
  /v1/example/send-notify/{cid}:
    post:
      consumes:
      - application/json
      description: คำอธิบาย API Send Moph Line Notification
      parameters:
      - description: CID
        in: path
        name: cid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Notification sent successfully
          schema:
            $ref: '#/definitions/dto.BaseResponse'
      summary: Send Moph Line Notification
      tags:
      - Example (ตัวอย่าง)
swagger: "2.0"
